# Generated by Django 4.2 on 2025-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('index', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='Index')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full name')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email')),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
